import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp} from '../src/server/app.ts';
async function fixture(){const dir=mkdtempSync(join(tmpdir(),'studio-test-'));const x=await createApp({dir,workers:false,bootstrapToken:'test-only-token'});await x.app.ready();return {...x,headers:{authorization:'Bearer test-only-token'},done:async()=>{await x.app.close();rmSync(dir,{recursive:true,force:true});}};}
test('API unauth and cross-site are rejected',async()=>{const x=await fixture();assert.equal((await x.app.inject('/api/v1/state')).statusCode,401);assert.equal((await x.app.inject({url:'/api/v1/state',headers:{...x.headers,origin:'http://evil.example'}})).statusCode,403);await x.done();});
test('simulate forces origin and creates safe print only',async()=>{const x=await fixture();const room=x.store.list('rooms')[0];const r=await x.app.inject({method:'POST',url:'/api/v1/simulate',headers:x.headers,payload:{roomId:room.id,type:'comment',text:'你好',nickname:'Test',count:1,origin:'live'}});assert.equal(r.statusCode,200);assert.equal(r.json().jobs.find((j:any)=>j.action==='print').status,'dry_run');await x.done();});
test('viewer cannot mutate nor read other room',async()=>{const x=await fixture();const [a,b]=x.store.list('rooms');const issued=await x.app.inject({method:'POST',url:'/api/v1/access',headers:x.headers,payload:{role:'viewer',roomIds:[a.id]}});const headers={authorization:'Bearer '+issued.json().token};assert.equal((await x.app.inject({url:'/api/v1/state',headers})).json().rooms.length,1);assert.equal((await x.app.inject({method:'POST',url:`/api/v1/rooms/${b.id}/connect`,headers})).statusCode,403);await x.done();});
test('overlay token cannot access admin or acknowledge print',async()=>{const x=await fixture();const room=x.store.list('rooms')[0];assert.equal((await x.app.inject({url:'/api/v1/state',headers:{authorization:'Bearer '+room.overlayToken}})).statusCode,401);const sim=await x.app.inject({method:'POST',url:'/api/v1/simulate',headers:x.headers,payload:{roomId:room.id,type:'comment',text:'你好',nickname:'Test',count:1}});const j=sim.json().jobs.find((j:any)=>j.action==='print');assert.equal((await x.app.inject({method:'POST',url:`/api/v1/overlay/${room.id}/ack?token=${room.overlayToken}`,payload:{jobId:j.id}})).statusCode,400);await x.done();});
test('unknown print cannot retry blindly',async()=>{const x=await fixture();const room=x.store.list('rooms')[0];x.store.put('jobs',{id:'uncertain',roomId:room.id,action:'print',origin:'live',status:'unknown'});const r=await x.app.inject({method:'POST',url:'/api/v1/jobs/uncertain/retry',headers:x.headers});assert.equal(r.statusCode,400);assert.equal(x.store.get('jobs','uncertain').status,'unknown');await x.done();});
test('settings rejects external AI endpoint',async()=>{const x=await fixture();const r=await x.app.inject({method:'POST',url:'/api/v1/settings',headers:x.headers,payload:{aiUrl:'http://169.254.169.254'}});assert.equal(r.statusCode,400);await x.done();});
test('operator cannot rebind physical printer',async()=>{const x=await fixture();const [a]=x.store.list('rooms');x.store.put('printers',{id:'other'});const issued=await x.app.inject({method:'POST',url:'/api/v1/access',headers:x.headers,payload:{role:'operator',roomIds:[a.id]}});const r=await x.app.inject({method:'PATCH',url:`/api/v1/rooms/${a.id}`,headers:{authorization:'Bearer '+issued.json().token},payload:{printerId:'other'}});assert.equal(r.statusCode,403);await x.done();});
